/// Flutter icons Fonts
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Fonts
///      fonts:
///       - asset: fonts/Fonts.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Fonts {
  Fonts._();

  static const _kFontFam = 'Fonts';

  static const IconData model = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData notifications =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData calendar =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData drive = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData app4car = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData thief = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData diagnostic =
      const IconData(0xe808, fontFamily: _kFontFam);
}
