import 'package:flutter/widgets.dart';

/// Flutter icons Fonts
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Fonts
///      fonts:
///       - asset: fonts/Fonts.ttf
///
///
///

class App4Car {
  App4Car._();

  static const _kFontFam = 'Fonts';

  static const IconData modelIcon =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData notificationsIcon =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData calendarIcon =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData driveIcon =
      const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData app4carIcon =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData thiefIcon =
      const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData diagnosticIcon =
      const IconData(0xe808, fontFamily: _kFontFam);

  static const appName = "App4Car";
  static const myCars = "Meus carros";
  static const password = "Password";
  static const username = "Username";
  static const login = "Entrar";

  static const addCar = "Adicionar novo";
  static const carModel = "Modelo";
  static const carBrand = "Marca";
  static const carYear = "Ano";
}
